[package]
name = "bincrypt"
version = "0.3.0"
authors = ["frk <hazefrk+dev@gmail.com>"]
description = "Encrypt a file using XSalsa20-Poly1305!"
documentation = "https://github.com/frk1/bincrypt"
homepage = "https://github.com/frk1/bincrypt"
repository = "https://github.com/frk1/bincrypt"
keywords = ["encryption", "file", "decryption"]
categories = ["command-line-utilities"]
license = "MIT"
build = "build.rs"

[dependencies]
base64 = "0.9.0"
failure = "0.1.1"
rust_sodium = "0.7.0"
structopt = "0.1.6"
structopt-derive = "0.1.6"

[package.metadata.winres]
ProductName = "bincrypt"
OriginalFilename = "bincrypt.exe"
LegalCopyright = "MIT-License"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
